language: ruby
cache: bundler
sudo: false
dist: precise
branches:
  only: master
before_install:
  - travis_retry gem update --system
  - travis_retry gem install bundler --no-document
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6.2
matrix:
  include:
    - rvm: 2.2
      before_install:
        - travis_retry gem update --system 2.7.8
        - travis_retry gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
        - travis_retry gem install bundler -v '< 2'
